#
#spring:
#  application:
#    name: caam-user-service
##  cloud:
##    config:
##      uri: http://localhost:8088
#
#
#
#server:
#  port: 8082
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061

#spring:
#  profiles:
#     active: prod
#server:
#  port: 8082
eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka