#
#spring:
#  application:
#    name: caam-user-service
##  cloud:
##    config:
##      uri: http://localhost:8088
#
#
#
#server:
#  port: 8082
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061
server:
  port: 8082
eureka:
  instance:
    hostname: 3.19.55.32
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://3.17.189.246:8761/eureka
